import 'package:flutter/material.dart';

class MyWrap extends StatelessWidget {
  const MyWrap({super.key});

  @override
  Widget build(BuildContext context) {
    return const Wrap(
      // alignment: WrapAlignment.spaceEvenly,
      crossAxisAlignment: WrapCrossAlignment.start,
      direction: Axis.vertical,
      spacing: 5,
      textDirection: TextDirection.rtl,
      children: <Widget>[
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('C'),
        SizedBox(height: 10, width: 15),
        Text('C++'),
        SizedBox(height: 10, width: 15),
        Text('Python'),
        SizedBox(height: 10, width: 10),
        Text('Django'),
        SizedBox(height: 10, width: 10),
        Text('C#'),
        SizedBox(height: 10, width: 10),
        Text('Java'),
        SizedBox(height: 10, width: 30),
        Text('Dart'),
        SizedBox(height: 10, width: 10),
        Text('Flutter'),
      ],
    );
  }
}
